// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	MinPrice      int64
	MaxPrice      int64
	Location      string
	PropertyType  string
	ContactMethod string
}

type Favorite struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ListingID uuid.UUID
}

type Listing struct {
	ID           uuid.UUID
	AgentID      uuid.UUID
	Title        string
	Description  string
	Price        int64
	Location     string
	Latitude     sql.NullFloat64
	Longtitude   sql.NullFloat64
	PropertyType string
	Verified     bool
	Images       json.RawMessage
	Status       string
	CreatedAt    time.Time
}

type Notification struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ListingID     uuid.UUID
	SentAt        time.Time
	Contact       string
	ContactMethod string
	Status        string
	Subject       string
	Body          string
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber sql.NullString
	Role        string
	Password    string
	CreatedAt   time.Time
	CompanyName sql.NullString
	Verified    bool
	Rating      float64
}
