// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Agent struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CompanyName sql.NullString
	Verified    sql.NullBool
	Rating      sql.NullFloat64
}

type Alert struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	MinPrice      string
	MaxPrice      string
	Location      string
	Type          string
	ContactMethod string
}

type Favourite struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ListingID uuid.UUID
}

type Listing struct {
	ID          uuid.UUID
	AgentID     uuid.UUID
	Title       string
	Description string
	RentType    string
	Price       string
	Location    string
	Latitude    sql.NullFloat64
	Longtitude  sql.NullFloat64
	Type        string
	Verified    sql.NullBool
	Images      json.RawMessage
	Status      string
	CreatedAt   sql.NullTime
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ListingID uuid.UUID
	SentAt    sql.NullTime
	Status    string
}

type User struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber sql.NullString
	Role        string
	Password    string
	CreatedAt   sql.NullTime
}
