// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	MinPrice      sql.NullInt64
	MaxPrice      sql.NullInt64
	Location      string
	PropertyType  string
	ContactMethod string
}

type Notification struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SentAt        time.Time
	Contact       string
	ContactMethod string
	Status        string
	Subject       string
	Body          string
}
